default_twitter: &default_twitter
  twitter_api_key: 'jk49tPVZyzl1q2hXTq6pbdaAJ'
  twitter_api_secret: '5cmfpGUcw90QasSs4pqH8ud5Y44jTxl1eK8WPtvnZDLlHwObzT'

development:
  secret_key_base: #長い文字列
  <<: *default_twitter

test:
  secret_key_base: #長い文字列
  <<: *default_twitter

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>